import { Coordinate } from '@core/utils/canvas/index';
import { ProductId } from '@magic/shared/product';

/** every product the scene places, so no edge can name a node that is absent */
export type WelcomeProductId = Exclude<ProductId, 'dev' | 'welcome'>;

export type WelcomeArrangement = {
  /** names the layout for whoever is editing these, never shown to a visitor */
  name: string;
  /**
   * placement relative to the other nodes, in world units. the origin these are
   * written against is arbitrary, only the distances between them matter, and no
   * offset may Y = |220|
   */
  nodes: Record<WelcomeProductId, Coordinate>;
  /** [source, target] pairs, drawn once every node has animated in */
  edges: [WelcomeProductId, WelcomeProductId][];
};

export const welcomeArrangements: WelcomeArrangement[] = [
  {
    name: 'zigzag',
    nodes: {
      'set-theory': { x: -560, y: 120 },
      'minimum-spanning-trees': { x: -336, y: -120 },
      'path-finding': { x: -112, y: 120 },
      'binary-search-trees': { x: 112, y: -120 },
      traversals: { x: 336, y: 120 },
      'markov-chains': { x: 560, y: -120 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['minimum-spanning-trees', 'path-finding'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['binary-search-trees', 'traversals'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'traversals'],
      ['minimum-spanning-trees', 'binary-search-trees'],
      ['path-finding', 'traversals'],
    ],
  },
  {
    name: 'orbit',
    nodes: {
      'set-theory': { x: -490, y: 0 },
      'minimum-spanning-trees': { x: -220, y: -220 },
      'path-finding': { x: -220, y: 220 },
      'binary-search-trees': { x: 0, y: 0 },
      'markov-chains': { x: 490, y: -170 },
      traversals: { x: 490, y: 170 },
    },
    edges: [
      ['binary-search-trees', 'set-theory'],
      ['binary-search-trees', 'minimum-spanning-trees'],
      ['binary-search-trees', 'path-finding'],
      ['binary-search-trees', 'markov-chains'],
      ['binary-search-trees', 'traversals'],
      ['minimum-spanning-trees', 'set-theory'],
      ['set-theory', 'path-finding'],
      ['markov-chains', 'traversals'],
      ['traversals', 'markov-chains'],
    ],
  },
  {
    name: 'arc',
    nodes: {
      'set-theory': { x: -560, y: 211 },
      'minimum-spanning-trees': { x: -336, y: -71 },
      'path-finding': { x: -112, y: -211 },
      'binary-search-trees': { x: 112, y: -211 },
      traversals: { x: 336, y: -71 },
      'markov-chains': { x: 560, y: 211 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['minimum-spanning-trees', 'path-finding'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['binary-search-trees', 'traversals'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'traversals'],
      ['minimum-spanning-trees', 'traversals'],
      ['set-theory', 'markov-chains'],
    ],
  },
  {
    name: 'lattice',
    nodes: {
      'set-theory': { x: -400, y: -180 },
      'minimum-spanning-trees': { x: -400, y: 180 },
      'path-finding': { x: 0, y: -180 },
      'binary-search-trees': { x: 0, y: 180 },
      traversals: { x: 400, y: -180 },
      'markov-chains': { x: 400, y: 180 },
    },
    edges: [
      ['set-theory', 'path-finding'],
      ['path-finding', 'traversals'],
      ['traversals', 'path-finding'],
      ['minimum-spanning-trees', 'binary-search-trees'],
      ['binary-search-trees', 'markov-chains'],
      ['set-theory', 'minimum-spanning-trees'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['traversals', 'markov-chains'],
    ],
  },
  {
    name: 'spine',
    nodes: {
      'set-theory': { x: -540, y: 0 },
      'path-finding': { x: -360, y: -200 },
      'minimum-spanning-trees': { x: -180, y: 0 },
      'binary-search-trees': { x: 180, y: 0 },
      traversals: { x: 360, y: 200 },
      'markov-chains': { x: 540, y: 0 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['minimum-spanning-trees', 'binary-search-trees'],
      ['binary-search-trees', 'minimum-spanning-trees'],
      ['binary-search-trees', 'markov-chains'],
      ['markov-chains', 'binary-search-trees'],
      ['set-theory', 'path-finding'],
      ['path-finding', 'minimum-spanning-trees'],
      ['binary-search-trees', 'traversals'],
      ['traversals', 'markov-chains'],
    ],
  },
  {
    name: 'diamond',
    nodes: {
      'set-theory': { x: -600, y: 0 },
      'path-finding': { x: -280, y: 0 },
      'minimum-spanning-trees': { x: 0, y: -200 },
      'binary-search-trees': { x: 0, y: 200 },
      traversals: { x: 280, y: 0 },
      'markov-chains': { x: 600, y: 0 },
    },
    edges: [
      ['path-finding', 'minimum-spanning-trees'],
      ['minimum-spanning-trees', 'traversals'],
      ['traversals', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['minimum-spanning-trees', 'binary-search-trees'],
      ['set-theory', 'path-finding'],
      ['path-finding', 'set-theory'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'traversals'],
    ],
  },
  {
    name: 'wave',
    nodes: {
      'set-theory': { x: -550, y: 0 },
      'minimum-spanning-trees': { x: -330, y: 190 },
      'path-finding': { x: -110, y: 118 },
      'binary-search-trees': { x: 110, y: -118 },
      traversals: { x: 330, y: -190 },
      'markov-chains': { x: 550, y: 0 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['minimum-spanning-trees', 'path-finding'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['binary-search-trees', 'traversals'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'traversals'],
      ['set-theory', 'path-finding'],
      ['binary-search-trees', 'markov-chains'],
    ],
  },
  {
    name: 'chevron',
    nodes: {
      'set-theory': { x: -420, y: 0 },
      'minimum-spanning-trees': { x: -20, y: -160 },
      'path-finding': { x: -20, y: 160 },
      'binary-search-trees': { x: 240, y: 0 },
      traversals: { x: 420, y: -220 },
      'markov-chains': { x: 420, y: 220 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['set-theory', 'path-finding'],
      ['minimum-spanning-trees', 'binary-search-trees'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['binary-search-trees', 'traversals'],
      ['binary-search-trees', 'markov-chains'],
      ['minimum-spanning-trees', 'traversals'],
      ['path-finding', 'markov-chains'],
    ],
  },
  {
    name: 'funnel',
    nodes: {
      'set-theory': { x: -480, y: -220 },
      'minimum-spanning-trees': { x: -480, y: 220 },
      'path-finding': { x: -20, y: -120 },
      'binary-search-trees': { x: -20, y: 120 },
      traversals: { x: 480, y: -80 },
      'markov-chains': { x: 480, y: 80 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['set-theory', 'path-finding'],
      ['minimum-spanning-trees', 'binary-search-trees'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['path-finding', 'traversals'],
      ['binary-search-trees', 'markov-chains'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'traversals'],
    ],
  },
  {
    name: 'cascade',
    nodes: {
      'set-theory': { x: -550, y: -200 },
      'minimum-spanning-trees': { x: -330, y: -200 },
      'path-finding': { x: -110, y: 0 },
      'binary-search-trees': { x: 110, y: 0 },
      traversals: { x: 330, y: 200 },
      'markov-chains': { x: 550, y: 200 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['minimum-spanning-trees', 'path-finding'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['binary-search-trees', 'traversals'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'traversals'],
      ['minimum-spanning-trees', 'binary-search-trees'],
      ['path-finding', 'traversals'],
    ],
  },
  {
    name: 'bowtie',
    nodes: {
      'set-theory': { x: -560, y: -190 },
      'minimum-spanning-trees': { x: -560, y: 190 },
      'path-finding': { x: -120, y: 0 },
      'binary-search-trees': { x: 120, y: 0 },
      traversals: { x: 560, y: -190 },
      'markov-chains': { x: 560, y: 190 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['set-theory', 'path-finding'],
      ['minimum-spanning-trees', 'path-finding'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['binary-search-trees', 'traversals'],
      ['binary-search-trees', 'markov-chains'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'traversals'],
    ],
  },
  {
    name: 'triangle',
    nodes: {
      'set-theory': { x: -560, y: 190 },
      'minimum-spanning-trees': { x: -280, y: 0 },
      'path-finding': { x: 0, y: -190 },
      'binary-search-trees': { x: 0, y: 190 },
      traversals: { x: 280, y: 0 },
      'markov-chains': { x: 560, y: 190 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['minimum-spanning-trees', 'path-finding'],
      ['path-finding', 'traversals'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'binary-search-trees'],
      ['binary-search-trees', 'markov-chains'],
      ['binary-search-trees', 'set-theory'],
      ['minimum-spanning-trees', 'traversals'],
      ['traversals', 'minimum-spanning-trees'],
    ],
  },
  {
    name: 'benzene ring',
    nodes: {
      'set-theory': { x: -460, y: 0 },
      'minimum-spanning-trees': { x: -230, y: -210 },
      'path-finding': { x: 230, y: -210 },
      'binary-search-trees': { x: 460, y: 0 },
      traversals: { x: 230, y: 210 },
      'markov-chains': { x: -230, y: 210 },
    },
    edges: [
      ['set-theory', 'minimum-spanning-trees'],
      ['minimum-spanning-trees', 'set-theory'],
      ['minimum-spanning-trees', 'path-finding'],
      ['path-finding', 'binary-search-trees'],
      ['binary-search-trees', 'path-finding'],
      ['binary-search-trees', 'traversals'],
      ['traversals', 'markov-chains'],
      ['markov-chains', 'traversals'],
      ['markov-chains', 'set-theory'],
    ],
  },
];
